return {
  'nvimdev/dashboard-nvim',
  event = 'VimEnter',
  config = function()
    require('dashboard').setup {
      theme = 'doom',
      config = {
        header = {
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⢀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡇⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠘⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡀",
          "⢸⣿⣿⣷⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⡿⠀⠀⠀⠀⠀⠀⢠⠾⠿⠿⠿⠿⠿⠿⠿⠿⢦⡀⠀⠀⠀⠀⠀⠹⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣤⣶⣿⣿⡿",
          "⠀⢻⣿⣿⣿⣿⣿⣿⣶⣤⣀⡀⠀⠀⣰⣿⣿⣿⠃⠀⠀⠀⠀⠀⣴⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣹⡀⠀⠀⠀⠀⠀⢿⣿⣿⣧⠀⠀⠀⣀⣠⣴⣾⣿⣿⣿⣿⣿⣿⠁",
          "⠀⠈⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣿⣿⣿⡿⠀⠀⠀⠀⠀⣼⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣷⡀⠀⠀⠀⠀⢸⣿⣿⣿⣧⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀",
          "⠀⠀⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⢀⣼⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⡄⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀",
          "⠀⠀⠀⠈⠙⠛⠛⠛⠛⠿⠿⠿⣿⣿⣿⣿⣿⡇⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⡄⠀⠀⢀⣿⣿⣿⣿⣿⡿⠿⠿⠛⠛⠛⠛⠛⠉⠀⠀⠀",
          "⠀⠀⢀⣀⣀⣠⣤⣤⣤⣶⣶⣶⣿⣿⣿⣿⣿⣷⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣄⠀⢀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⢸⣿⣿⣿⣿⣿⣷⣶⣶⣦⣤⣤⣤⣀⣀⣀⠀⠀",
          "⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
          "⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇",
          "⠀⠘⣿⣿⣿⣿⣿⡿⠿⠛⠋⣁⣴⣾⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⢀⣾⣿⣿⡄⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣦⣌⠉⠛⠻⠿⣿⣿⣿⣿⣿⡏⠀",
          "⠀⠀⠘⠛⠛⠉⠁⠀⢀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⣼⣿⣿⣿⣷⡀⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⠀⠀⠉⠙⠛⠋⠀⠀",
          "⠀⠀⠀⠀⠀⢀⣤⣾⣿⣿⣿⣿⣿⣿⡿⠋⣸⣿⣿⣿⣿⣿⠋⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠘⢿⣿⣿⣿⣿⣯⠈⠻⣿⣿⣿⣿⣿⣿⣿⣦⣄⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣿⣿⡿⠋⠀⣰⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣧⠀⠈⢻⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⡿⠋⠀⠀⣠⣿⣿⣿⣿⣿⡏⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣷⠀⠀⠙⢿⣿⣿⠟⠁⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⢰⣿⣿⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⠙⠿⣿⣿⣿⣿⣿⡿⠛⠁⠀⠀⠀⠀⠀⢹⣿⣿⣿⣿⣿⣧⠀⠀⠀⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠉⠉⠁⠀⠀⣠⣶⣦⠀⠀⠀⠈⢻⣿⣿⠉⠀⠀⠀⢠⣶⣦⡀⠀⠀⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⠟⠁⠀⠀⠀⣀⣸⣿⣿⣀⡀⠀⠀⠀⠻⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⡿⠟⠁⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠈⠛⢿⡗⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣴⣶⣶⣶⣤⣀⡀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⣀⣤⣴⣶⣶⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡟⠛⠛⠛⠻⣿⣿⡆⠀⠀⠸⣿⣿⣿⣿⣿⡟⠀⠀⢀⣾⣿⠿⠛⠛⠛⢻⣿⡧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⡄⠀⠀⠀⠈⠛⠃⠀⠀⠀⢻⣿⣿⣿⣿⠁⠀⠀⠈⠛⠃⠀⠀⠀⠀⣼⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
          "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣈⡠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
        },
        center = {
          {
            icon = ' ',
            icon_hl = 'Title',
            desc = 'Find Files in Current Project                    ',
            desc_hl = 'String',
            key = 'f',
            key_hl = 'Number',
            key_format = ' [%s]',
            action = 'Telescope find_files',
          },
          {
            icon = ' ',
            icon_hl = 'Title',
            desc = 'Browse Recently Opened Files                    ',
            desc_hl = 'String',
            key = 'r',
            key_hl = 'Number',
            key_format = ' [%s]',
            action = 'Telescope oldfiles',
          },
          {
            icon = ' ',
            icon_hl = 'Title',
            desc = 'Switch to Different Project                     ',
            desc_hl = 'String',
            key = 'p',
            key_hl = 'Number',
            key_format = ' [%s]',
            action = 'Telescope projects',
          },
          {
            icon = ' ',
            icon_hl = 'Title',
            desc = 'Restore Previously Saved Session                ',
            desc_hl = 'String',
            key = 'l',
            key_hl = 'Number',
            key_format = ' [%s]',
            action = 'SessionLoad',
          },
          {
            icon = ' ',
            icon_hl = 'Title',
            desc = 'Choose and Apply Color Theme                    ',
            desc_hl = 'String',
            key = 't',
            key_hl = 'Number',
            key_format = ' [%s]',
            action = 'Themery',
          },
          {
            icon = ' ',
            icon_hl = 'Title',
            desc = 'Manage and Configure Plugins                    ',
            desc_hl = 'String',
            key = 'P',
            key_hl = 'Number',
            key_format = ' [%s]',
            action = 'Lazy',
          },
          {
            icon = ' ',
            icon_hl = 'Title',
            desc = 'Exit Neovim Editor                              ',
            desc_hl = 'String',
            key = 'q',
            key_hl = 'Number',
            key_format = ' [%s]',
            action = 'qa',
          },
        },
        footer = {
          '',
          'Why are you buying clothes from the soup store?',
          '',
        },
        vertical_center = true,
      }
    }
    -- Hide tabline on dashboard
    vim.api.nvim_create_autocmd("FileType", {
      pattern = "dashboard",
      callback = function()
        vim.opt_local.showtabline = 0
      end,
    })
  end,
  dependencies = { {'nvim-tree/nvim-web-devicons'}}
}
